# Generated by Django 4.0.6 on 2022-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_lastretrieved_reportedtweet_tweet_twitteruserscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedtweet',
            name='reported_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
