# Generated by Django 4.0.6 on 2022-07-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_twitteruser_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='profile_image_url',
        ),
    ]
