# Generated by Django 4.0.6 on 2022-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_twitteruser_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_news_text', models.TextField()),
                ('fake_news_score', models.BooleanField()),
            ],
            options={
                'db_table': 'fake_news_score',
            },
        ),
    ]
