# Generated by Django 4.0.6 on 2022-08-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_twitter_name_synctwitteraccount_twitter_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyncTwitterAccount',
        ),
    ]
