# Generated by Django 4.0.6 on 2022-08-11 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_favourited_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruserscore',
            name='last_retrieved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportedtweet',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
