# Generated by Django 4.0.6 on 2022-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_delete_reportedtweet_delete_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=255)),
                ('tweet_date', models.DateTimeField(null=True)),
                ('tweet_text', models.TextField(null=True)),
                ('predicted_hate_score', models.CharField(max_length=1, null=True)),
                ('predicted_fake_score', models.CharField(max_length=1, null=True)),
                ('flagged', models.CharField(default=0, max_length=1)),
                ('offensive_count', models.IntegerField(default=0)),
                ('hateful_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('fake_news_count', models.IntegerField(default=0)),
                ('admin_interjection', models.BooleanField(default=False)),
                ('admin_hate_result', models.CharField(max_length=1, null=True)),
                ('admin_news_result', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'tweet',
            },
        ),
    ]
