# Generated by Django 4.0.6 on 2022-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedUser',
            fields=[
                ('twitter_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_retrieved', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'last_retrieved',
            },
        ),
        migrations.DeleteModel(
            name='LastRetrieved',
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
