# Generated by Django 4.0.6 on 2022-08-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_searcheduser_delete_lastretrieved_tweet_retweet'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searcheduser',
            table='searched_user',
        ),
    ]
