# Generated by Django 4.0.6 on 2022-08-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_searcheduser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searcheduser',
            table='searched_user',
        ),
    ]
