# Generated by Django 4.0.6 on 2022-08-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_searcheduser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchedUser',
        ),
    ]
