# Generated by Django 4.0.6 on 2022-08-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_delete_searcheduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRetrieved',
            fields=[
                ('twitter_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_retrieved', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'last_retrieved',
            },
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweet',
        ),
    ]
