# Generated by Django 4.0.6 on 2022-08-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_news_text', models.TextField()),
                ('fake_news_score', models.BooleanField()),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fake_news_score',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=255)),
                ('tweet_date', models.DateTimeField(null=True)),
                ('tweet_text', models.TextField(null=True)),
                ('predicted_hate_score', models.CharField(max_length=1, null=True)),
                ('predicted_fake_score', models.CharField(max_length=1, null=True)),
                ('retweet', models.CharField(max_length=5, null=True)),
                ('flagged', models.CharField(default=0, max_length=1)),
                ('offensive_count', models.IntegerField(default=0)),
                ('hateful_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('fake_news_count', models.IntegerField(default=0)),
                ('admin_interjection', models.BooleanField(default=False)),
                ('admin_hate_result', models.CharField(max_length=1, null=True)),
                ('admin_news_result', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'tweet',
            },
        ),
        migrations.CreateModel(
            name='TwitterAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=255)),
                ('oauth_token_secret', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'website_twitter_auth_token',
            },
        ),
        migrations.CreateModel(
            name='TwitterUserScore',
            fields=[
                ('twitter_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hate_score', models.IntegerField()),
                ('fake_news_score', models.IntegerField()),
                ('last_retrieved', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'twitter_user_score',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
                ('twitter_oauth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.twitterauthtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_twitter_user',
            },
        ),
        migrations.CreateModel(
            name='SyncTwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_twitter',
            },
        ),
        migrations.CreateModel(
            name='Favourited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourited_twitter_id', models.CharField(max_length=255)),
                ('favourited_username', models.CharField(max_length=255)),
                ('soft_delete', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourited',
            },
        ),
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_twitter_id', models.CharField(max_length=255)),
                ('blocked_username', models.CharField(max_length=255)),
                ('soft_delete', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked',
            },
        ),
    ]
