# Generated by Django 4.0.6 on 2022-08-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweet',
        ),
    ]
