# Generated by Django 4.0.6 on 2022-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_twitterauthtoken_alter_customtwidectoruser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRetrieved',
            fields=[
                ('twitter_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_retrieved', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'last_retrieved',
            },
        ),
        migrations.CreateModel(
            name='ReportedTweet',
            fields=[
                ('reported_id', models.IntegerField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('reported_status', models.SmallIntegerField()),
                ('tweet_id', models.IntegerField(unique=True)),
                ('report_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'reported_tweet',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20, null=True)),
                ('tweet_date', models.DateTimeField(null=True)),
                ('tweet_text', models.TextField(null=True)),
                ('predicted_score', models.CharField(max_length=1)),
                ('flagged', models.CharField(max_length=1)),
                ('retweet', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tweet',
            },
        ),
        migrations.CreateModel(
            name='TwitterUserScore',
            fields=[
                ('twitter_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hate_score', models.IntegerField()),
                ('fake_news_score', models.IntegerField()),
            ],
            options={
                'db_table': 'twitter_user_score',
            },
        ),
    ]
