# Generated by Django 4.0.6 on 2022-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_tweet_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
