# Generated by Django 4.0.6 on 2022-08-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tweet_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='fitted_hate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='fitted_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
