# Generated by Django 4.0.6 on 2022-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_reportedtweet_reported_id_alter_tweet_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtwidectoruser',
            name='email',
            field=models.EmailField(max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customtwidectoruser',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
