# Generated by Django 4.0.6 on 2022-08-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_tweet_fitted_hate_tweet_fitted_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.TextField()),
                ('hate_score', models.IntegerField()),
            ],
            options={
                'db_table': 'hate_score',
            },
        ),
    ]
