# Generated by Django 4.0.6 on 2022-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_customtwidectoruser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='profile_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='twitterauthtoken',
            table='website_twitter_auth_token',
        ),
        migrations.DeleteModel(
            name='CustomTwidectorUser',
        ),
    ]
