# Generated by Django 4.0.6 on 2022-08-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_twitter_id_synctwitteraccount_twitter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synctwitteraccount',
            old_name='twitter_name',
            new_name='twitter_id',
        ),
    ]
