# Generated by Django 4.0.6 on 2022-08-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_synctwitteraccount_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='synctwitteraccount',
            table='sync_twitter',
        ),
    ]
