# Generated by Django 4.0.6 on 2022-08-08 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_synctwitteraccount_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakenews',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
