# Generated by Django 4.0.6 on 2022-08-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_fakenews_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='predicted_fake_news_score',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
