# Generated by Django 4.0.6 on 2022-08-11 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0019_tweet_predicted_fake_news_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourited_twitter_id', models.CharField(max_length=255)),
                ('favourited_username', models.CharField(max_length=255)),
                ('soft_delete', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourited',
            },
        ),
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_twitter_id', models.CharField(max_length=255)),
                ('blocked_username', models.CharField(max_length=255)),
                ('soft_delete', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked',
            },
        ),
    ]
