# Generated by Django 4.0.6 on 2022-08-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_twitteruserscore_last_retrieved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportedTweet',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
